name: pokedex_carbonica
description: "Pokédex desarrollada en Flutter usando GraphQL y PokeAPI."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  shared_preferences: ^2.2.2
  share_plus: ^10.1.3
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8

  graphql_flutter: ^5.1.2
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1

  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.0
  riverpod_generator: ^2.3.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # Habilita la generación automática de AppLocalizations
  generate: true

  assets:
    - lib/assets/

  # Carpeta de localización (ARB)
  # Asegúrate de tener tus archivos .arb dentro de /lib/l10n/
  # Ejemplo:
  # - lib/l10n/


